extend backup&account&parameter
alibabacloud-automation/terraform-alicloud-polardb-postgresql pull request #2
Opened 2023-10-30 11:16 UTC by tortoise-daddy

terraform-alicloud-polardb-postgresql supports the configuration of accounts, parameters, level-1 backup and level-2 backup

2023-10-30 11:38 UTC, xiaozhu36 requested changes

2023-10-30 11:38 UTC, xiaozhu36 commented on main.tf
> +  db_type            = var.db_type
这个地方没必要改，因为这个module 特指的就是创建 PG 数据库

2023-10-30 11:38 UTC, xiaozhu36 commented on variables.tf
> +    value   = "10000"
为啥要设置这个Default 值

2023-10-30 11:44 UTC, tortoise-daddy commented on variables.tf
> +    value   = "10000"
terrform的入参规定 name和value不能为空，所以必须有一个输入。选择的参数和值为创建实例时的默认值，所以参数值实际上没有变化。

2023-10-30 11:48 UTC, tortoise-daddy commented on main.tf
> +  db_type            = var.db_type
我们PolarDB-PG 除了 PostgreSQL ,还有一个 Oracle兼容性的版本db_type 是Oracle。tf-provider 是支持的

2023-10-31 01:59 UTC, xiaozhu36 requested changes

2023-10-31 01:59 UTC, xiaozhu36 commented on main.tf
> +  db_type            = var.db_type
db_type 总共支持三种引擎：MySQL，Oracle，PostgreSQL，这三种引擎在创建的时候，存在较大的差异性，强烈建议 Oracle 申请为一个独立的 Module

2023-10-31 01:59 UTC, xiaozhu36 commented on variables.tf
> +    value   = "10000"
terraform 的入参中，parameters 是必填的，这个跟 OpenAPI 是对齐的，如果创建实例时会默认创建 parameters，那么目前 terraform provider 应该存在问题，这个需要先修复。

2023-10-31 02:20 UTC, tortoise-daddy commented on variables.tf
> +    value   = "10000"
terraform 的入参中，parameters 不是必填的，但是在moudl里面如果需要支持修改参数paramters就要添加进去。paramters的name和value是必填的，我觉得这个有修改的空间。这次modul的发布我把parameters的默认值去掉，后续我再修改provider paramters的name和value

2023-10-31 02:23 UTC, tortoise-daddy commented on main.tf
> +  db_type            = var.db_type
我觉得 Polardb-PG openapi、tf 层面、甚至后端的任务逻辑 Oracle 和 PostgreSQL 两种引擎都没有较大的差异。但是本次发布我暂时去掉 db_type,默认 PostgreSQL 。具体需不需要申请一个独立的Module我们后面讨论

2023-10-31 02:24 UTC, tortoise-daddy commented on variables.tf
> +    value   = "10000"
polardb-mysql 的paramters也是这种现状

2023-10-31 04:15 UTC, xiaozhu36 requested changes

2023-10-31 04:15 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  create_endpoint               = false
这个为啥号改成 false

2023-10-31 04:15 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  create_endpoint_address       = false
还有这个

2023-10-31 04:20 UTC, tortoise-daddy commented on examples/complete/main.tf
> +  create_endpoint_address       = false
与endpoint同理，因为polardb-pg 样例中创建的企业版，enpoint 在创建cluster时是会默认创建的。这个create_endpoint再次创建集群地址会重复，只能创建自定义地址，所以我改成了false，我可以可以改成创建自定义地址

2023-10-31 04:20 UTC, tortoise-daddy commented on examples/complete/main.tf
> +  create_endpoint               = false
因为polardb-pg 样例中创建的企业版，enpoint 在创建cluster时是会默认创建的。这个create_endpoint再次创建集群地址会重复，只能创建自定义地址，所以我改成了false，我可以可以改成创建自定义地址

2023-10-31 04:51 UTC, tortoise-daddy commented
#example运行成功
![ECA1558C-280A-43CB-9D89-ADFAD8F62B96](https://github.com/alibabacloud-automation/terraform-alicloud-polardb-postgresql/assets/37547381/0deedfa8-b259-47b1-b6a9-a4b67d338ccd)
#成功创建PolarDB-PG 实例
![3672EDD0-9B2B-42FA-9102-33A4F5440899](https://github.com/alibabacloud-automation/terraform-alicloud-polardb-postgresql/assets/37547381/13ba1065-4948-4953-a2d5-eb9677fc2d0b)
#新增一个RO
![C11BD223-7867-4191-9CE3-A61D83D046F9](https://github.com/alibabacloud-automation/terraform-alicloud-polardb-postgresql/assets/37547381/3d60b345-c00d-408f-b063-f51355c23e62)
#开启ssl

2023-10-31 04:51 UTC, tortoise-daddy commented
#开启ssl

2023-10-31 05:48 UTC, xiaozhu36 requested changes

2023-10-31 05:48 UTC, xiaozhu36 commented on variables.tf
> +  type        = map(string)
parameters 在 provider 中是一个List，因此如果想让这个module 支持设置多个 parameter 的话，类型应该是 list（map）

2023-10-31 06:02 UTC, tortoise-daddy commented on variables.tf
> +  type        = map(string)
本次变更只支持设置一个paramter

2023-10-31 06:40 UTC, tortoise-daddy commented on variables.tf
> +  type        = map(string)
支持了多个paramter

2023-10-31 06:45 UTC, xiaozhu36 approved these changes

2023-10-31 06:46 UTC, merged