Support resource: alicloud_polardb_cluster_endpoint, alicloud_polardb_primary_endpoint. Support modify connect port.
alibabacloud-automation/terraform-alicloud-polardb-postgresql pull request #9
Opened 2024-02-02 16:21 UTC by tortoise-daddy

测试结果：

2024-02-03 12:39 UTC, xiaozhu36 requested changes

2024-02-03 12:39 UTC, xiaozhu36 commented on main.tf
> +  count             = lookup(var.cluster_endpoint, "endpoint", null) != null ? 1 : 0
使用for_each 代替 count

2024-02-03 12:39 UTC, xiaozhu36 commented on main.tf
> +  count             = lookup(var.cluster_endpoint, "endpoint", null) != null ? 1 : 0
其他也类似

2024-02-03 12:39 UTC, xiaozhu36 commented on variables.tf
> +  default     = null
这个的默认值为啥要改

2024-02-03 12:39 UTC, xiaozhu36 commented on variables.tf
> +  type        = any
如果是 map 的话，就应该明确声明为 map(string)

2024-02-03 15:03 UTC, tortoise-daddy commented on variables.tf
> +  default     = null
ssl_auto_rotate 参数polardb-pg 不支持，以前被别人误加到module里面，为了做兼容的变更，选择把default置为null，而没有直接去掉这个参数

2024-02-03 15:05 UTC, tortoise-daddy commented on variables.tf
> +  type        = any
![A7788509-DB25-4728-BCE2-35D827CDC719](https://github.com/alibabacloud-automation/terraform-alicloud-polardb-postgresql/assets/37547381/b4be4a0f-aef4-402f-a5da-628ea792eefb)
这部分是参考AWS设计的，这里面的map应该不等同于数据结构的map，只是字面上的映射的含义

2024-02-03 15:10 UTC, tortoise-daddy commented on main.tf
> +  count             = lookup(var.cluster_endpoint, "endpoint", null) != null ? 1 : 0
![image](https://github.com/alibabacloud-automation/terraform-alicloud-polardb-postgresql/assets/37547381/0ec5ad1f-1a4d-443d-a8fe-242be8c020f1)
图中为在example中给出的cluster_endpoint的示例，endpoint代表 endpoint 资源本身后续还会加入ssl 等功能，public_address 只代表公网地址不代表同一个资源，而且polardb 的集群地址和主地址随着集群创建、有且只有一个，无法使用for_each。

2024-02-04 05:56 UTC, ChenHanZhang reviewed
approved

2024-02-04 06:09 UTC, merged